### ISSUE TITLE
typo: Linux Torvalds

### ISSUE THREAD

**Issue by tooru** [keiichishima/tanenbaum_minix_article#1]
はじめまして。
翻訳ありがとうございます。楽しく読まさせていただきました。

1箇所「Linu**x** Torvalds」と書かれているところがありましたのでご報告いたします。

https://github.com/keiichishima/tanenbaum_minix_article/blame/d2a6c7f6eb673dfd098ec0a7e87ff226d3e6a505/Lessons_learned_from_30_years_of_Minix-JP.md#L49

**Comment by keiichishima** [comment]
ありがとうございます！修正させていただきました。
